routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/years', function(){
    $json_data = file_get_contents('datos.txt');
    $data = collect(json_decode($json_data, true));
    // dd($data[0]);
    dd($data->where('birthYear' < 100)->get());
});
Route::get('/', function () {
    return view('landing.home');
});
Route::get('/empresa', function () {
    return view('landing.empresa');
})->name('empresa');
Route::get('/contacto', function () {
    return view('landing.contacto');
})->name('contacto');
Route::get('/ayuda', function () {
    return view('landing.ayuda');
})->name('ayuda');
Route::get('/empleos', function () {
    return view('landing.empleos');
})->name('empleos');
Route::get('/tutorial', function () {
    return view('landing.tutorial');
})->name('tutorial');
Route::get('/anunciate', function () {
    return view('landing.anunciate');
})->name('anunciate');
Route::get('/fake', function () {
    return view('index_fake');
});
Route::get('/terms', function () {
    return view('landing.terms');
});

Auth::routes();
Route::post('register_made', 'Auth\RegisterController@create')->name('register_made');
Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function(){
    Route::resource('cupons', 'CuponsController');
    Route::resource('post', 'PostsController');
    Route::resource('area', 'AreasController');

    Route::resource('payments', 'PaymentsController');

    Route::resource('owner', 'OwnersController');

    Route::resource('complains', 'ComplainsController');
    Route::get('admin/area/add_marker', 'AreasController@addMarker')->name('area.addMarker');
    Route::get('admin/area/{area}/delete', 'AreasController@deleteMarker')->name('area.delete');

    Route::get('/admin/logout', function(){
        \Auth::logout();
        return redirect()->to('/');
    })->name('admin.logout');
});
Route::get('/home', 'HomeController@index')->name('home');

app/Models/FeedPhoto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\User;
class FeedPhoto extends Model
{
    //

    public function getImageAttribute($value){
        return "http://api.bashout.app/public/feed_photo/".$value;
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ComplainsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Complaint;
use Illuminate\Http\Request;

class ComplainsController extends Controller
{
    protected $section = "complains";

    public function __construct(Request $request){
        $this->middleware(function ($request, $next) {
            if(\Auth::user()->type_of_user != 2 && \Auth::user()->type_of_user != 3)
                return redirect()->route('cupons.index');
            return $next($request);
        });
    }

    public function index(){

        return view('admin.complains.index')
                ->with('complains', Complaint::latest()->get())
                ->with('section', $this->section);
    }

    public function destroy($id){
        $complain = Complaint::find($id);
        if($complain->type == "Event")
            $complain->post->delete();
        if($complain->type == "Me And Friends Photo")
            $complain->maf->delete();
        if($complain->type == "Event Image")
            $complain->eventPhoto->delete();
        $complain->delete();
        return back();
    }

}

resources/views/admin/complains/index.blade.php
@extends('admin.layouts.app')
@section('breadcrumb')
    <ol class="breadcrumb pull-right">
        <li class="active"><a href="javascript:;">Complains</a></li>
    </ol>
@endsection
@section('header')
    Complains <small>see all the complains</small>
@endsection
@section('content')
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                </div>
                <h4 class="panel-title">Existing complains</h4>
            </div>
            <div class="panel-body">
                <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
                    <thead>
                        <tr>
                            <th>Complainer</th>
                            <th>Post</th>
                            <th>Post User</th>
                            <th>Type</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($complains as $key => $complain)
                            <tr class=" gradeC">
                                <td>{{ $complain->user->user_name }}</td>
                                @if($complain->type == "Event")
                                    <td>{{ $complain->post->title }}</td>
                                    <td>{{ $complain->post->user->user_name }}</td>
                                @endif
                                @if($complain->type == "Me And Friends Photo")
                                    <td align="center">
                                        <img src="{{ $complain->maf->image }}" alt="" class="img-responsive" style="width: 300px;">
                                    </td>
                                    <td>{{ $complain->maf->user->user_name }}</td>
                                @endif
                                @if($complain->type == "Event Image")
                                    <td align="center">
                                        <img src="{{ $complain->eventPhoto->image }}" alt="" class="img-responsive" style="width: 300px;">
                                    </td>
                                    <td>{{ $complain->eventPhoto->user->user_name }}</td>
                                @endif

                                <td>{{ $complain->type }}</td>
                                <td>
                                    <p>
                                        <a class="btn btn-danger btn-icon btn-circle btn-sm delete" product="{{ $complain->id }}">
                                            <i class="fa fa-times"></i>
                                        </a>
                                        <form class="form{{ $complain->id }}" action="{{ route('complains.destroy', $complain->id) }}" method="post">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE">
                                        </form>
                                    </p>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end panel -->
    </div>
@endsection
@section('js')
    <script src="{{ asset('js/assets/postsIndex.js') }}"></script>

@endsection