routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/years', function(){
    $json_data = file_get_contents('datos.txt');
    $data = collect(json_decode($json_data, true));
    // dd($data[0]);
    dd($data->where('birthYear' < 100)->get());
});
Route::get('/', function () {
    return view('landing.home');
});
Route::get('/empresa', function () {
    return view('landing.empresa');
})->name('empresa');
Route::get('/contacto', function () {
    return view('landing.contacto');
})->name('contacto');
Route::get('/ayuda', function () {
    return view('landing.ayuda');
})->name('ayuda');
Route::get('/empleos', function () {
    return view('landing.empleos');
})->name('empleos');
Route::get('/tutorial', function () {
    return view('landing.tutorial');
})->name('tutorial');
Route::get('/anunciate', function () {
    return view('landing.anunciate');
})->name('anunciate');
Route::get('/fake', function () {
    return view('index_fake');
});
Route::get('/terms', function () {
    return view('landing.terms');
});

Auth::routes();
Route::post('register_made', 'Auth\RegisterController@create')->name('register_made');
Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function(){
    Route::resource('cupons', 'CuponsController');
    Route::resource('post', 'PostsController');
    Route::resource('area', 'AreasController');

    Route::resource('payments', 'PaymentsController');

    Route::resource('owner', 'OwnersController');

    Route::resource('complains', 'ComplainsController');
    Route::get('admin/area/add_marker', 'AreasController@addMarker')->name('area.addMarker');
    Route::get('admin/area/{area}/delete', 'AreasController@deleteMarker')->name('area.delete');

    Route::get('/admin/logout', function(){
        \Auth::logout();
        return redirect()->to('/');
    })->name('admin.logout');
});
Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="es">
<!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<title>BashOut</title>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />

	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
	<link href="{{ asset('plugins/jquery-ui/themes/base/minified/jquery-ui.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('plugins/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('css/animate.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('css/style.css') }}" rel="stylesheet" />
	<link href="{{ asset('css/style-responsive.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('css/theme/default.css') }}" rel="stylesheet" id="theme" />
	<!-- ================== END BASE CSS STYLE ================== -->

	<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
	<link href="{{ asset('plugins/jquery-jvectormap/jquery-jvectormap.css') }}" rel="stylesheet" />
	<link href="{{ asset('plugins/sweetalert2/dist/sweetalert2.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('plugins/bootstrap-datepicker/css/bootstrap-datepicker.css') }}" rel="stylesheet" />
    <link href="{{ asset('plugins/gritter/css/jquery.gritter.css') }}" rel="stylesheet" />
    <link href="{{ asset('plugins/DataTables/media/css/dataTables.bootstrap.min.css') }}" rel="stylesheet" />
	<link href="{{ asset('plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css') }}" rel="stylesheet" />
	<!-- ================== END PAGE LEVEL STYLE ================== -->

	<!-- ================== BEGIN BASE JS ================== -->
	<script src="{{ asset('plugins/pace/pace.min.js') }}"></script>
	<!-- ================== END BASE JS ================== -->

    @yield('css')
</head>
<body>
	<!-- begin #page-loader -->
	<div id="page-loader" class="fade in"><span class="spinner"></span></div>
	<!-- end #page-loader -->

	<!-- begin #page-container -->
	<div id="page-container" class="fade page-sidebar-fixed page-header-fixed">
		<!-- begin #header -->
		<div id="header" class="header navbar navbar-default navbar-fixed-top">
			<!-- begin container-fluid -->
			<div class="container-fluid">
				<!-- begin mobile sidebar expand / collapse button -->
				<div class="navbar-header">
					<a href="#" class="navbar-brand"><span class="navbar-logo"></span>BashOut</a>
					<button type="button" class="navbar-toggle" data-click="sidebar-toggled">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<!-- end mobile sidebar expand / collapse button -->

				<!-- begin header navigation right -->
				<ul class="nav navbar-nav navbar-right">

					<li class="dropdown navbar-user">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
							<img src="assets/img/user-13.jpg" alt="" />
							<span class="hidden-xs">{{ \Auth::user()->name }} {{ \Auth::user()->last_name }}</span> <b class="caret"></b>
						</a>
						<ul class="dropdown-menu animated fadeInLeft">
							<li class="arrow"></li>
							{{-- <li><a href="javascript:;">Edit Profile</a></li>
							<li><a href="javascript:;"><span class="badge badge-danger pull-right">2</span> Inbox</a></li>
							<li><a href="javascript:;">Calendar</a></li>
							<li><a href="javascript:;">Setting</a></li>
							<li class="divider"></li> --}}
							<li><a href="{{ route('admin.logout') }}">Logout</a></li>
						</ul>
					</li>
				</ul>
				<!-- end header navigation right -->
			</div>
			<!-- end container-fluid -->
		</div>
		<!-- end #header -->

		<!-- begin #sidebar -->
		<div id="sidebar" class="sidebar">
			<!-- begin sidebar scrollbar -->
			<div data-scrollbar="true" data-height="100%">
				<!-- begin sidebar user -->
				<ul class="nav">
					<li class="nav-profile">
						{{-- <div class="image">
							<a href="javascript:;"><img src="assets/img/user-13.jpg" alt="" /></a>
						</div> --}}
						<div class="info">
							{{ \Auth::user()->name }} {{ \Auth::user()->last_name }}
							{{-- <small>Front end developer</small> --}}
						</div>
					</li>
				</ul>
				<!-- end sidebar user -->
				<!-- begin sidebar nav -->
				<ul class="nav">
                    @if(\Auth::user()->type_of_user == 1)
                        <li class="{{ $section == "cupons" ? "active" : "" }}">
                            <a href="{{ route('cupons.index') }}">
                                <i class="fa fa-ticket"></i> <span>Cupones</span>
                            </a>
                        </li>
                        <li class="{{ $section == "posts" ? "active" : "" }}">
                            <a href="{{ route('post.index') }}">
                                <i class="fa fa-address-book"></i> <span>Posts</span>
                            </a>
                        </li>

                        <li class="{{ $section == "area" ? "active" : "" }}">
                            <a href="{{ route('area.index') }}">
                                <i class="fa fa-map"></i> <span>Areas</span>
                            </a>
                        </li>
                        <li class="{{ $section == "cupons" ? "active" : "" }}">
                            <a href="{{ route('payments.index') }}">
                                <i class="fa fa-money"></i> <span>Payments</span>
                            </a>
                        </li>
                    @endif
                    @if(\Auth::user()->type_of_user == 2 || \Auth::user()->type_of_user == 3)
                        <li class="{{ $section == "complains" ? "active" : "" }}">
                            <a href="{{ route('complains.index') }}">
                                <i class="fa fa-clipboard"></i> <span>Denuncias</span>
                            </a>
                        </li>
                    @endif
                    @if(\Auth::user()->type_of_user == 3)
                        <li class="{{ $section == "owner" ? "active" : "" }}">
                            <a href="{{ route('owner.index') }}">
                                <i class="fa fa-lock"></i> <span>Usuarios</span>
                            </a>
                        </li>
                    @endif
                    {{-- <li class="{{ $section == "payments" ? "active" : "" }}">
                        <a href="">
                            <i class="fa fa-money"></i> <span>Payments</span>
                        </a>
                    </li> --}}

			        <!-- begin sidebar minify button -->
					<li><a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-double-left"></i></a></li>
			        <!-- end sidebar minify button -->
				</ul>
				<!-- end sidebar nav -->
			</div>
			<!-- end sidebar scrollbar -->
		</div>
		<div class="sidebar-bg"></div>
		<!-- end #sidebar -->

		<!-- begin #content -->
		<div id="content" class="content">

            @yield('breadcrumb')

			<!-- begin page-header -->
			<h1 class="page-header">@yield('header')</h1>
			<!-- end page-header -->

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @yield('content')

		</div>
		<!-- end #content -->

		<!-- begin scroll to top btn -->
		<a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
		<!-- end scroll to top btn -->
	</div>
	<!-- end page container -->

	<!-- ================== BEGIN BASE JS ================== -->
	<script src="{{ asset('plugins/jquery/jquery-1.9.1.min.js') }}"></script>
	<script src="{{ asset('plugins/jquery/jquery-migrate-1.1.0.min.js') }}"></script>
	<script src="{{ asset('plugins/jquery-ui/ui/minified/jquery-ui.min.js') }}"></script>
	<script src="{{ asset('plugins/bootstrap/js/bootstrap.min.js') }}"></script>
	<script src="{{ asset('plugins/parsleyjs/dist/parsley.min.js') }}"></script>
	<!--[if lt IE 9]>
		<script src="assets/crossbrowserjs/html5shiv.js"></script>
		<script src="assets/crossbrowserjs/respond.min.js"></script>
		<script src="assets/crossbrowserjs/excanvas.min.js"></script>
	<![endif]-->
	<script src="{{ asset('plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>
	<script src="{{ asset('plugins/jquery-cookie/jquery.cookie.js') }}"></script>
	<!-- ================== END BASE JS ================== -->

	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{{ asset('plugins/sweetalert2/dist/sweetalert2.min.js') }}"></script>
	<script src="{{ asset('plugins/gritter/js/jquery.gritter.js') }}"></script>
	<script src="{{ asset('plugins/flot/jquery.flot.min.js') }}"></script>
	<script src="{{ asset('plugins/flot/jquery.flot.time.min.js') }}"></script>
	<script src="{{ asset('plugins/flot/jquery.flot.resize.min.js') }}"></script>
	<script src="{{ asset('plugins/flot/jquery.flot.pie.min.js') }}"></script>
	<script src="{{ asset('plugins/sparkline/jquery.sparkline.js') }}"></script>
	<script src="{{ asset('plugins/jquery-jvectormap/jquery-jvectormap.min.js') }}"></script>
	<script src="{{ asset('plugins/jquery-jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
	<script src="{{ asset('plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}"></script>
	<script src="{{ asset('js/dashboard.js') }}"></script>
	<script src="{{ asset('js/apps.min.js') }}"></script>
    <script src="{{ asset('plugins/DataTables/media/js/jquery.dataTables.js') }}"></script>
	<script src="{{ asset('plugins/DataTables/media/js/dataTables.bootstrap.min.js') }}"></script>
	<script src="{{ asset('plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('plugins/angular/angular.min.js') }}"></script>
    <script src="{{ asset('plugins/angular-animate/angular-animate.min.js') }}"></script>
    @yield('js')
	<!-- ================== END PAGE LEVEL JS ================== -->

	<script>
		$(document).ready(function() {
			App.init();
			// Dashboard.init();
		});
	</script>
</body>
</html>