routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/years', function(){
    $json_data = file_get_contents('datos.txt');
    $data = collect(json_decode($json_data, true));
    // dd($data[0]);
    dd($data->where('birthYear' < 100)->get());
});
Route::get('/', function () {
    return view('landing.home');
});
Route::get('/empresa', function () {
    return view('landing.empresa');
})->name('empresa');
Route::get('/contacto', function () {
    return view('landing.contacto');
})->name('contacto');
Route::get('/ayuda', function () {
    return view('landing.ayuda');
})->name('ayuda');
Route::get('/empleos', function () {
    return view('landing.empleos');
})->name('empleos');
Route::get('/tutorial', function () {
    return view('landing.tutorial');
})->name('tutorial');
Route::get('/anunciate', function () {
    return view('landing.anunciate');
})->name('anunciate');
Route::get('/fake', function () {
    return view('index_fake');
});
Route::get('/terms', function () {
    return view('landing.terms');
});

Auth::routes();
Route::post('register_made', 'Auth\RegisterController@create')->name('register_made');
Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function(){
    Route::resource('cupons', 'CuponsController');
    Route::resource('post', 'PostsController');
    Route::resource('area', 'AreasController');

    Route::resource('payments', 'PaymentsController');

    Route::resource('owner', 'OwnersController');

    Route::resource('complains', 'ComplainsController');
    Route::get('admin/area/add_marker', 'AreasController@addMarker')->name('area.addMarker');
    Route::get('admin/area/{area}/delete', 'AreasController@deleteMarker')->name('area.delete');

    Route::get('/admin/logout', function(){
        \Auth::logout();
        return redirect()->to('/');
    })->name('admin.logout');
});
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Post extends Model
{
    //
    protected $table = "events";
    protected $fillable = [
        'user_id',
        'title',
        'description',
        'contact',
        'street_name',
        'city',
        'state',
        'zip_code',
        'lat',
        'lon',
        'charge',
        'date',
        'time',
        'end_date',
        'cover_image'
    ];
    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Validator;

class PostsController extends Controller
{
    public $section = "posts";
    public function __construct(Request $request){
        $this->middleware(function ($request, $next) {
            if(\Auth::user()->type_of_user != 1)
                return redirect()->route('complains.index');
            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $posts = Post::where('user_id', \Auth::id())->get();
        return view('admin.posts.index')
                ->with('posts', $posts)
                ->with('section', $this->section);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.posts.create')
                ->with('section', $this->section);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $rules = [
            'user_id' => 'required',
            'title' => 'required',
            'description' => 'required',
            'contact' => 'required',
            'street_name' => 'required',
            'city' => 'required',
            'state' => 'required',
            'zip_code' => 'required',
            'lat' => 'required',
            'lon' => 'required',
            'charge' => 'sometimes',
            'date' => 'required',
            'time' => 'required',
            'end_date' => 'required',
            'cover_image' => 'required|image',
        ];
        $validation = Validator::make($request->all(), $rules);
        if($validation->fails())
            return redirect()->back()->withErrors($validation->messages());
        $newName = uniqid("", true).".".$request->file('cover_image')->getClientOriginalExtension();
        $request->file('cover_image')->storeAs(
            'event_images', $newName, 'public'
        );
        $post = Post::create($request->except(['_token', 'cover_image']));
        $post->cover_image = $newName;
        $post->save();
        return redirect()->route('post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
        $post->delete();
        return back();
    }
}

resources/views/admin/posts/create.blade.php
@extends('admin.layouts.app')
@section('css')
    <link rel="stylesheet" href="{{ asset('plugins/angular-ui-bootstrap/dist/ui-bootstrap-csp.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/angular-ui-bootstrap/src/datepicker/datepicker.css') }}">
    <ling rel="stylesheet" href="{{ asset('plugins/bootstrap-eonasdan-datetimepicker/build/css/bootstrap-datetimepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/angular-ui-select/dist/select.css') }}">
@endsection

@section('breadcrumb')
    <ol class="breadcrumb pull-right">
        <li><a href="{{ route('post.index') }}">Posts</a></li>
        <li class="active"><a href="#">Create</a></li>
    </ol>
@stop
@section('header')
    Create Posts <small>Fill the form to create a new post</small>
@endsection
@section('content')
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                </div>
                <h4 class="panel-title">Create Post</h4>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" data-parsley-validate enctype="multipart/form-data" action="{{ route('post.store') }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="user_id" value="{{ \Auth::id() }}">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Title</label>
                        <div class="col-md-9">
                            <input
                                data-parsley-type="text"
                                required
                                class="form-control"
                                placeholder="Title of the event"
                                name="title">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Description</label>
                        <div class="col-md-9">
                            <input
                                data-parsley-type="text"
                                required
                                class="form-control"
                                placeholder="Description of the event"
                                name="description">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Contact</label>
                        <div class="col-md-9">
                            <input
                                data-parsley-type="text"
                                required
                                class="form-control"
                                placeholder="Contact to the event"
                                name="contact">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Street Name</label>
                        <div class="col-md-9">
                            <input
                                data-parsley-type="text"
                                required
                                class="form-control"
                                placeholder="Street name of the event"
                                name="street_name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">City</label>
                        <div class="col-md-9">
                            <input
                                data-parsley-type="text"
                                required
                                class="form-control"
                                placeholder="City of the event"
                                name="city">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">State</label>
                        <div class="col-md-9">
                            <input
                                data-parsley-type="text"
                                required
                                class="form-control"
                                placeholder="State of the event"
                                name="state">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Zip Code</label>
                        <div class="col-md-9">
                            <input
                                data-parsley-type="digits"
                                required
                                class="form-control"
                                placeholder="Zip Code of the event"
                                name="zip_code">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Charge</label>
                        <div class="col-md-9">
                            <input
                                data-parsley-type="number"
                                required
                                class="form-control"
                                placeholder="Cost of the event, leave blank if does not apply"
                                name="charge">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Start Date</label>
                        <div class="col-md-9">
                            <div class="input-group date" data-provide="datepicker" data-date-start-date="0d" data-date-format="yyyy-mm-dd">
                                <input type="text" name="date" placeholder="Day of the event" class="form-control" required="">
                                <div class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Start Hour</label>
                        <div class="col-md-9">
                            <div class="input-group bootstrap-timepicker timepicker" data-provide="timepicker" data-template="modal" data-minute-step="1" data-modal-backdrop="true">
                                <input id="timepicker1" type="text" class="form-control input-small" name="time">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">End Date</label>
                        <div class="col-md-9">
                            <div class="input-group bootstrap-datetimepicker timepicker">
                                <input id="datetimepicker" type="text" placeholder="End date/hour of event" class="form-control input-small" name="end_date">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Cover Image</label>
                        <div class="col-md-9">
                            <input type="file" class="form-control" name="cover_image" accept="image/*">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Location</label>
                        <div class="col-md-9">
                            <div id="google_map" style="width:800px;height:400px;"></div>
                        </div>
                    </div>
                    <input type="hidden" name="lat" id="lat" value="20.660373502829383">
                    <input type="hidden" name="lon" id="lon" value="-103.34980487823486">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Save</label>
                        <div class="col-md-9">
                            <button type="submit" class="btn btn-sm btn-success">Store existence</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript" src="{{ asset('plugins/moment/moment.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('plugins/bootstrap-eonasdan-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8sjVJWe2hfkWqrvZgEZV8x5a2AENKzDs&callback=initMap" type="text/javascript"></script>

    <script type="text/javascript">
    function initMap(){
        var myLatlng = {lat: 20.660373502829383, lng: -103.34980487823486};

        var map = new google.maps.Map(document.getElementById('google_map'), {
          zoom: 15,
          center: myLatlng
        });

        var marker = new google.maps.Marker({
          position: myLatlng,
          map: map,
          draggable:true,
          title: 'Click to zoom'
        });

        map.addListener('click', function(e) {
            // 3 seconds after the center of the map has changed, pan back to the
            // marker.
            // alert(e.latLng.lat());
            marker.setPosition(e.latLng);
            document.getElementById('lat').value = e.latLng.lat();
            document.getElementById('lon').value = e.latLng.lng();
            // window.setTimeout(function() {
            //     map.panTo(marker.getPosition());
            // }, 3000);
        });

    }
    $(function () {
        $('#datetimepicker').datetimepicker({
            minDate: moment()
        });
    });
        $('#timepicker1').timepicker({
            minuteStep: 1,
            template: 'modal',
            appendWidgetTo: 'body',
            showSeconds: false,
            showMeridian: false
        });
    </script>
@endsection

resources/views/admin/posts/index.blade.php
@extends('admin.layouts.app')
@section('breadcrumb')
    <ol class="breadcrumb pull-right">
        <li class="active"><a href="javascript:;">Posts</a></li>
    </ol>
@endsection
@section('header')
    Posts <small>manage the existing post</small>
    <a class="btn btn-success btn-icon btn-circle btn-sm" href="{{ route('post.create') }}">
        <i class="fa fa-plus"></i>
    </a>
@endsection
@section('content')
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                </div>
                <h4 class="panel-title">Existing products</h4>
            </div>
            <div class="panel-body">
                <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>End Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($posts as $key => $post)
                            <tr class=" gradeC">
                                <td>{{ $post->title }}</td>
                                <td>
                                    {{ $post->description }}
                                </td>
                                <td>
                                    {{ Carbon\Carbon::parse($post->date)->toFormattedDateString() }}
                                </td>
                                <td>
                                    {{ $post->time }}
                                </td>
                                <td>
                                    {{ Carbon\Carbon::parse($post->end_date)->toDayDateTimeString() }}
                                </td>
                                <td>
                                    <p>
                                        <a class="btn btn-danger btn-icon btn-circle btn-sm delete" product="{{ $post->id }}">
                                            <i class="fa fa-times"></i>
                                        </a>
                                        <form class="form{{ $post->id }}" action="{{ route('post.destroy', $post) }}" method="post">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE">
                                        </form>
                                    </p>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end panel -->
    </div>
@endsection
@section('js')
    <script src="{{ asset('js/assets/postsIndex.js') }}"></script>

@endsection