routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/years', function(){
    $json_data = file_get_contents('datos.txt');
    $data = collect(json_decode($json_data, true));
    // dd($data[0]);
    dd($data->where('birthYear' < 100)->get());
});
Route::get('/', function () {
    return view('landing.home');
});
Route::get('/empresa', function () {
    return view('landing.empresa');
})->name('empresa');
Route::get('/contacto', function () {
    return view('landing.contacto');
})->name('contacto');
Route::get('/ayuda', function () {
    return view('landing.ayuda');
})->name('ayuda');
Route::get('/empleos', function () {
    return view('landing.empleos');
})->name('empleos');
Route::get('/tutorial', function () {
    return view('landing.tutorial');
})->name('tutorial');
Route::get('/anunciate', function () {
    return view('landing.anunciate');
})->name('anunciate');
Route::get('/fake', function () {
    return view('index_fake');
});
Route::get('/terms', function () {
    return view('landing.terms');
});

Auth::routes();
Route::post('register_made', 'Auth\RegisterController@create')->name('register_made');
Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function(){
    Route::resource('cupons', 'CuponsController');
    Route::resource('post', 'PostsController');
    Route::resource('area', 'AreasController');

    Route::resource('payments', 'PaymentsController');

    Route::resource('owner', 'OwnersController');

    Route::resource('complains', 'ComplainsController');
    Route::get('admin/area/add_marker', 'AreasController@addMarker')->name('area.addMarker');
    Route::get('admin/area/{area}/delete', 'AreasController@deleteMarker')->name('area.delete');

    Route::get('/admin/logout', function(){
        \Auth::logout();
        return redirect()->to('/');
    })->name('admin.logout');
});
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Area.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    //
    protected $fillable = ["user_id", "lat", "lon", "radio"];
}

app/Http/Controllers/AreasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Area;
use Illuminate\Http\Request;

class AreasController extends Controller
{
    protected $section = "area";
    public function __construct(Request $request){
        $this->middleware(function ($request, $next) {
            if(\Auth::user()->type_of_user != 1)
                return redirect()->route('cupons.index');
            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $areas = \Auth::user()->areas;
        return view('admin.areas.index')
                ->with('areas', $areas)
                ->with('section', $this->section);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $user = \Auth::user();

        $user->areas()->delete();
        $areas = [];
        foreach ($request->lat as $key => $value) {
            # code...
            $insert = [
                'user_id' => $user->id,
                'lat' =>  $request->lat[$key],
                'lon' => $request->lon[$key],
                'radio' => $request->radio[$key],
            ];
            $areas[] = Area::create($insert)->id;
        }
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function show(Area $area)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function edit(Area $area)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Area $area)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function destroy(Area $area)
    {
        //
    }

    public function addMarker(){
        Area::create([
            'lat' => 20.660373502829383,
            'lon' => -103.34980487823486,
            'radio' => 1000,
            'user_id' => \Auth::id(),
        ]);
        return back();
    }

    public function deleteMarker(Area $area){
        if ($area)
            $area->delete();
        return back();
    }
}

resources/views/admin/areas/index.blade.php
@extends('admin.layouts.app')
@section('css')
    <link rel="stylesheet" href="{{ asset('plugins/angular-ui-bootstrap/dist/ui-bootstrap-csp.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/angular-ui-bootstrap/src/datepicker/datepicker.css') }}">
    <ling rel="stylesheet" href="{{ asset('plugins/bootstrap-eonasdan-datetimepicker/build/css/bootstrap-datetimepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/angular-ui-select/dist/select.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/ionRangeSlider/css/ion.rangeSlider.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/ionRangeSlider/css/ion.rangeSlider.skinFlat.css') }}">
@endsection

@section('breadcrumb')
    <ol class="breadcrumb pull-right">
        <li><a href="{{ route('area.index') }}">Areas</a></li>
        <li class="active"><a href="#">Manage</a></li>
    </ol>
@stop
@section('header')
    Manage Areas <small>Move and rearrange areas</small>
@endsection
@section('content')
    <div class="col-md-12">
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                </div>
                <h4 class="panel-title">Manage Areas</h4>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" data-parsley-validate enctype="multipart/form-data" action="{{ route('area.store') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label class="col-md-3 control-label">Save Locations</label>
                        <div class="col-md-9">
                            <button type="submit" class="form-control btn btn-sm btn-success">Save Locations</button>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Location</label>
                        <div class="col-md-9">
                            <div id="google_map" style="width:800px;height:400px;"></div>
                        </div>
                    </div>
                    @foreach ($areas as $key => $area)
                        <div class="form-group">
                            <label class="col-md-3 control-label">Marker #{{ $key+1 }}</label>
                            <div class="col-md-8">
                                <input type="text" id="slider_{{ $key }}" name="" value="">
                                <input type="hidden" id="lat_{{ $key }}" name="lat[]" value="{{ $area->lat }}">
                                <input type="hidden" id="lon_{{ $key }}" name="lon[]" value="{{ $area->lon }}">
                                <input type="hidden" id="radio_{{ $key }}" name="radio[]" value="{{ $area->radio }}">
                            </div>
                            <div class="col-md-1">
                                <a href="{{ route('area.delete', $area) }}">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                    @endforeach
                </form>
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Add Marker</label>
                        <div class="col-md-9">
                            <a href="{{ route('area.addMarker') }}" class="btn btn-info">Add Marker</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8sjVJWe2hfkWqrvZgEZV8x5a2AENKzDs&callback=initMap" type="text/javascript"></script>
<script type="text/javascript" src="{{ asset('plugins/ionRangeSlider/js/ion-rangeSlider/ion.rangeSlider.min.js') }}"></script>
<script type="text/javascript">
    var markers = [];
    var circles = [];
    var sliders = [];
    function initMap(){
        var areas = JSON.parse(JSON.stringify({!! $areas->toJson() !!}));
        var myLatlng = {lat: 20.660373502829383, lng: -103.34980487823486};

        var map = new google.maps.Map(document.getElementById('google_map'), {
            zoom: 15,
            center: myLatlng
        });
        for(i = 0; i < areas.length; i++) {
            position = {lat: parseFloat(areas[i].lat), lng: parseFloat(areas[i].lon)};
            markers[i] = new google.maps.Marker({
                position: position,
                map: map,
                draggable:true,
                ownId: i,
                title: 'Click to zoom'
            });
            circles[i] = new google.maps.Circle({
                map: map,
                fillColor: "#27fff1",
                strokeColor: "#35ff94",
                strokeOpacity: 0.8,
                radius: parseInt(areas[i].radio)
            });
            circles[i].bindTo('center', markers[i], 'position');
            markers[i].addListener('dragend', function(e) {
                var id = $(this)[0].ownId.toString();
                document.getElementById('lat_'+id).value = e.latLng.lat();
                document.getElementById('lon_'+id).value = e.latLng.lng();
            });
            var circulo = circles[i];
            sliders[i] = $("#slider_"+i).ionRangeSlider({
                min: 0,
                max: 100000,
                step: 10,
                from: parseInt(areas[i].radio),
                postfix: "m",
            });
            sliders[i].on('change', function(e){
                id = parseInt(e.currentTarget.id.replace("slider_", ""));
                var $this = $(this),
                value = parseInt($this.prop("value"));
                document.getElementById('radio_'+id).value = value;
                circles[id].setRadius(value);
            });
        }
        // map.addListener('click', function(e) {
        //     marker.setPosition(e.latLng);
        //     document.getElementById('lat').value = e.latLng.lat();
        //     document.getElementById('lon').value = e.latLng.lng();
        // });

    }
</script>
@endsection